version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    
    entrypoint: 
      - /bin/sh
      - -c
      - | 
        ollama serve &
        sleep 5
        echo "Verifica modello llama3.1..."
        ollama pull llama3.1
        wait
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  ollama_data: